<<<<<<< HEAD
=======
<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_integrador
spring.datasource.username=postgres
spring.datasource.password=nova_senha
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
=======
>>>>>>> 8d723c75dea8e98c051b7ee5bdebfd20b5e0e829
# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_integrador
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
<<<<<<< HEAD
=======
>>>>>>> 642918d614cd2e5e6344c70451602c5148974576
>>>>>>> 8d723c75dea8e98c051b7ee5bdebfd20b5e0e829
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

<<<<<<< HEAD
=======
<<<<<<< HEAD
server.port=8080

app.jwt-secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt-expiration-milliseconds=604800000
=======
>>>>>>> 8d723c75dea8e98c051b7ee5bdebfd20b5e0e829
# Server
server.port=8080

# Logging
logging.level.br.pucgo.ads.projetointegrador=DEBUG
logging.level.org.springframework.web=DEBUG

# JWT Configuration
app.jwt-secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt-expiration-milliseconds=604800000

# Tamanho máximo de arquivo enviado, alterar para enviar o csv
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
<<<<<<< HEAD
=======
>>>>>>> 642918d614cd2e5e6344c70451602c5148974576
>>>>>>> 8d723c75dea8e98c051b7ee5bdebfd20b5e0e829
